IG_forum/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^forum/', include('forum.urls')),
	url(r'^authent/', include('authent.urls')),
    url(r'^admin/', admin.site.urls),
]

authent/urls.py
from django.conf.urls import url

from . import views

app_name = 'authent'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^signout/$',views.signout,name='logout'),
]

forum/urls.py
from django.conf.urls import url

from . import views

app_name = 'forum'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
]

authent/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

forum/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.db import models
class Question(models.Model):
	question_text = models.CharField(max_length= 255 )
	pub_time = models.DateTimeField('pub_time')
	upvotes = models.IntegerField(default = 0)
	downvotes = models.IntegerField(default = 0)
	def __str__(self):
		return self.question_text

class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	answer_text = models.CharField(max_length=255)
	answer_time = models.TimeField('ans_time')
	upvotes = models.IntegerField(default = 0)
	downvotes = models.IntegerField(default = 0)
	auser = models.ForeignKey(User , on_delete=models.CASCADE)
	def __str__(self):
		return self.answer_text

class Qcomment(models.Model):
	cquestion = models.ForeignKey('Question', on_delete=models.CASCADE)
	qcomment_text = models.CharField(max_length=255)
	qcomment_time = models.TimeField('qcomment_time')
	qcuser = models.ForeignKey(
        User , 
        on_delete=models.CASCADE,
        
        
    )
	def __str__(self):
		return self.qcomment_text

class Acomment(models.Model):
	answer = models.ForeignKey('Answer' , on_delete=models.CASCADE)
	acomment_text = models.CharField(max_length=255)
	acomment_time = models.DateTimeField('acomment_time')
	acuser = models.ForeignKey(
        User , 
        on_delete=models.CASCADE,

    )
	def __str__(self):
		return self.acomment_text

		

authent/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from django.contrib.auth.models import User
import json
# Create your views here.

def index(request):

	if request.user.is_authenticated():
		return redirect('/forum')
	else:
		return redirect('/authent/signin')

def signout(request):
	#print "logging out" this also clears all session data
	logout(request) 
	return redirect('/authent/')


def signin(request):
	if request.user.is_authenticated() == True:
		return redirect('/forum')
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		if user is None:
			return render(request,'signin.html',{'error':'Invalid username or password'})

		else:
			login(request,user)
			return redirect('/forum/') #render the forum page
	else:
		return render(request,'signin.html',None)

def signup(request):
	if request.user.is_authenticated() == True:
		return redirect('/forum')
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		password2 = request.POST['password2']
		firstName = request.POST['firstName']
		lastName = request.POST['lastName']
		if password2 != password:
			return render(request,'signup.html',{'error':'Password doesn\'t match'}) 

		emailAddr = request.POST['email']

		try:
			u = User._default_manager.get(username__iexact=username) #fix for case sensitive username
			return render(request,'signup.html',{'error':'username already already exists!'})
		except User.DoesNotExist:
			user = User.objects.create_user(username=username,email=emailAddr,first_name=firstName,last_name=lastName)
			user.set_password(password)
			user.save()
			user.backend = 'django.contrib.authent.backends.ModelBackend' #user backend error fix
			authenticate(username=username,password=password)
			login(request,user)
			return redirect('/forum/')
	else:
		return render(request,'signup.html',None)

forum/views.py
from django.shortcuts import render
from django.http import	HttpResponse 
from django.shortcuts import render , get_object_or_404 , redirect
from .models import Question
'''#This will show recent questions , signup ,signin options 
(no of answers, no of votes,no of comments,time published , published by ,) for questions '''
def index(request): #This request object contains meta data about request
   	if request.user.is_authenticated() == True:
	    latest_question_list = Question.objects.order_by('-pub_time')[:10]
	    context = {'latest_question_list': latest_question_list}
	    return render(request, 'index.html', context) #This return a response object
	else:
		return redirect('/authent')

'''This will show particular question text , publishion time of question ,
user who published , Commenting on question ,show comments , upvotes , downvote on question.


Show Top answers with upvotes 
votes on answers
comments on answers
add answers.'''
def detail(request,question_id):
	question = get_object_or_404(Question, pk=question_id)
	answer = question.answer_set.all().order_by( '-upvotes')[:5]
	return render(request , 'detail.html' , {'question' : question , 'answer' : answer})

	if request.method == 'POST':
		question.answer_set.create(answer_text = request.POST['ans_text'])

templates/base.html
{% load staticfiles %}
<head>
  <title>{% block title %}{% endblock %}</title>

  <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
  <script type="text/javascript" src = "{% static 'css/materialize/js/materialize.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/materialize/css/materialize.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> 
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">
</head>
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper  green darken-1">
    <a href="#!" class="brand-logo">IGConnect</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Home</a></li>
      <li>{{username}}</li>
      <li><a href="badges.html">Profile</a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Settings<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

{%block content %}
{% endblock %}

<footer class="page-footer green darken-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>



<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src = "{% static 'css/materialize/js/materialize.min.js' %}"></script>

templates/detail.html
<h1> ANSWER BOX </h1>
<form action = "{% url 'forum:detail' question.id %}"  method = "post" >
{% csrf_token %}
<textarea>
</textarea><br>
<input type = 'submit' value=" Enter your text here" name = "ans_text">
</form>

templates/index.html
{% load staticfiles %}
<head>
  <title>{% block title %}BASIC FORUM PAGE{% endblock %}</title>

  <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
  <script type="text/javascript" src = "{% static 'css/materialize/js/materialize.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/materialize/css/materialize.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> 
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">
</head>
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li> 
</ul>
<nav>
  <div class="nav-wrapper  green darken-1">
    <a href="#!" class="brand-logo">IGConnect</a>
    <ul class="right hide-on-med-and-down">
      <li>{{user.first_name}} {{user.last_name}} </li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Settings<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

{%block content %}


  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center">Latest questions</a>
    </div>
  </nav>

 

{% if latest_question_list %}
    <div class="collection">
    {% for question in latest_question_list %}
    <a href="{% url 'forum:detail' question.id %}" class="collection-item"><h5>{{forloop.counter}}) {{ question.question_text }}</h5><span class="badge"></span></a>
    <a class="waves-effect waves-light btn">upvotes:{{question.upvotes}}</a>
    <a class="waves-effect waves-light btn">downvotes:{{question.downvotes}} </a>
    <a class="waves-effect waves-light btn">published on :{{question.pub_time}}</a>
    <a class="waves-effect waves-light btn">Answers : {{question.answer_set.count}}</a>
    <a class="waves-effect waves-light btn">Comments : {{question.qcomment_set.count}}</a>
    <a class="waves-effect waves-light btn">Published by {{question.qcomment_set.count}}</a>
    {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}




{% endblock %}

<footer class="page-footer green darken-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>



<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src = "{% static 'css/materialize/js/materialize.min.js' %}"></script>

templates/signin.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}

{% block content %}
{% if error  %}
  <div class="chip">
    <div class = "material-icons">error_outline</div>{{error}}
    <i class="material-icons">close</i>
  </div>
{% endif %}
<div class = "row">
	<form class = "col s12" action = "{% url 'authent:signin' %}" method = "post">
		{% csrf_token %}
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "username" required="">
				<label for="first_name">Username</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="password" class="validate" name = "password" required="">
				<label for="first_name">password</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s6">
				<input type="submit" class="validate btn green darken-4" name = "Sign up">
			</div>
		</div>
	</form>
</div>
<div class = "row">
	<a href = "{% url 'authent:signup'%}">Signup!</a>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}
Signup
{% endblock %}

{% block content %}
{% if error  %}
  <div class="chip">
    <div class = "material-icons">error_outline</div>{{error}}
    <i class="material-icons">close</i>
  </div>
{% endif %}
<div class = "row">
	<form class = "col s12" action = "{% url 'authent:signup' %}" method = "post">
		{% csrf_token %}
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "username" required="">
				<label for="first_name">Username</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "firstName" required="">
				<label for="first_name">First Name</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate" name = "lastName" required="">
				<label for="first_name">Last Name</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="password" class="validate" name = "password" required="">
				<label for="first_name">password</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="password" class="validate" name = "password2" required="">
				<label for="first_name">Re-type password</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s4">
				<input type="email" class="validate" name = "email" required="">
				<label for="first_name">email-address</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field col s6">
				<input type="submit" class="validate btn green darken-4" name = "Sign up">
			</div>
		</div>
	</form>
</div>
{% endblock %}